#!/bin/bash

################################################################################
# HSQLDB SimilarWeb Database Setup Script
# Purpose: Complete setup for similarweb_db with schema initialization
################################################################################

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DB_NAME="similarweb_db"
DB_PATH="${SCRIPT_DIR}/data/${DB_NAME}"
SERVER_PORT=9001
HSQLDB_VERSION="2.7.4"
HSQLDB_JAR="${SCRIPT_DIR}/lib/hsqldb.jar"
SQLTOOL_JAR="${SCRIPT_DIR}/lib/sqltool.jar"
LOG_DIR="${SCRIPT_DIR}/logs"
PID_FILE="${SCRIPT_DIR}/${DB_NAME}.pid"

# Function to print colored messages
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Function to check if Java is installed
check_java() {
    print_info "Checking Java installation..."
    if ! command -v java &> /dev/null; then
        print_error "Java is not installed. Please install Java JDK 8 or higher."
        exit 1
    fi
    
    JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
    if [ "$JAVA_VERSION" -lt 8 ]; then
        print_error "Java version 8 or higher is required. Current version: $JAVA_VERSION"
        exit 1
    fi
    print_success "Java is installed (version: $(java -version 2>&1 | head -n 1))"
}

# Function to download HSQLDB if not present
download_hsqldb() {
    if [ -f "$HSQLDB_JAR" ] && [ -f "$SQLTOOL_JAR" ]; then
        print_success "HSQLDB jars found"
        return
    fi
    
    print_info "HSQLDB jars not found. Downloading HSQLDB ${HSQLDB_VERSION}..."
    mkdir -p "${SCRIPT_DIR}/lib"
    
    DOWNLOAD_URL="https://sourceforge.net/projects/hsqldb/files/hsqldb/hsqldb_2_7/hsqldb-${HSQLDB_VERSION}.zip/download"
    TEMP_ZIP="${SCRIPT_DIR}/lib/hsqldb.zip"
    
    if command -v wget &> /dev/null; then
        wget -O "$TEMP_ZIP" "$DOWNLOAD_URL" || {
            print_error "Failed to download HSQLDB. Please download manually from http://hsqldb.org/"
            exit 1
        }
    elif command -v curl &> /dev/null; then
        curl -L -o "$TEMP_ZIP" "$DOWNLOAD_URL" || {
            print_error "Failed to download HSQLDB. Please download manually from http://hsqldb.org/"
            exit 1
        }
    else
        print_error "Neither wget nor curl found. Please install one or download HSQLDB manually."
        exit 1
    fi
    
    print_info "Extracting HSQLDB..."
    unzip -q "$TEMP_ZIP" -d "${SCRIPT_DIR}/lib/temp"
    cp "${SCRIPT_DIR}/lib/temp/hsqldb-${HSQLDB_VERSION}/hsqldb/lib/hsqldb.jar" "$HSQLDB_JAR"
    cp "${SCRIPT_DIR}/lib/temp/hsqldb-${HSQLDB_VERSION}/hsqldb/lib/sqltool.jar" "$SQLTOOL_JAR"
    rm -rf "${SCRIPT_DIR}/lib/temp" "$TEMP_ZIP"
    
    print_success "HSQLDB downloaded and extracted successfully"
}

# Function to create directory structure
create_directories() {
    print_info "Creating directory structure..."
    mkdir -p "$(dirname "$DB_PATH")"
    mkdir -p "$LOG_DIR"
    mkdir -p "${SCRIPT_DIR}/sql"
    mkdir -p "${SCRIPT_DIR}/lib"
    print_success "Directories created"
}

# Function to create SQL initialization script
create_init_sql() {
    print_info "Creating database initialization SQL script..."
    
    cat > "${SCRIPT_DIR}/sql/init_similarweb_db.sql" << 'EOF'
-- ============================================
-- SimilarWeb Database Schema
-- Purpose: Track web analytics, competitor data, and traffic metrics
-- ============================================

-- Drop existing tables (for clean initialization)
DROP TABLE IF EXISTS traffic_metrics CASCADE;
DROP TABLE IF EXISTS keyword_rankings CASCADE;
DROP TABLE IF EXISTS referring_sites CASCADE;
DROP TABLE IF EXISTS social_media_metrics CASCADE;
DROP TABLE IF EXISTS competitor_analysis CASCADE;
DROP TABLE IF EXISTS websites CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

-- Categories table: Website categories/industries
CREATE TABLE categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    parent_category_id INTEGER,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_parent_category FOREIGN KEY (parent_category_id) REFERENCES categories(category_id)
);

-- Websites table: Track monitored websites
CREATE TABLE websites (
    website_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(255) NOT NULL UNIQUE,
    website_name VARCHAR(255),
    category_id INTEGER,
    country VARCHAR(3), -- ISO country code
    global_rank INTEGER,
    country_rank INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

-- Traffic Metrics table: Historical traffic data
CREATE TABLE traffic_metrics (
    metric_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_id INTEGER NOT NULL,
    measurement_date DATE NOT NULL,
    total_visits BIGINT,
    unique_visitors BIGINT,
    page_views BIGINT,
    pages_per_visit DECIMAL(10,2),
    avg_visit_duration INTEGER, -- in seconds
    bounce_rate DECIMAL(5,2), -- percentage
    direct_traffic_pct DECIMAL(5,2),
    referral_traffic_pct DECIMAL(5,2),
    search_traffic_pct DECIMAL(5,2),
    social_traffic_pct DECIMAL(5,2),
    paid_traffic_pct DECIMAL(5,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_website_metrics FOREIGN KEY (website_id) REFERENCES websites(website_id),
    CONSTRAINT unique_website_date UNIQUE (website_id, measurement_date)
);

-- Keyword Rankings table: SEO keyword tracking
CREATE TABLE keyword_rankings (
    ranking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_id INTEGER NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    search_engine VARCHAR(50) DEFAULT 'Google',
    ranking_position INTEGER,
    search_volume INTEGER,
    measurement_date DATE NOT NULL,
    organic_traffic_share DECIMAL(5,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_website_keywords FOREIGN KEY (website_id) REFERENCES websites(website_id)
);

-- Referring Sites table: Traffic source websites
CREATE TABLE referring_sites (
    referral_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_id INTEGER NOT NULL,
    referring_domain VARCHAR(255) NOT NULL,
    referral_visits INTEGER,
    referral_percentage DECIMAL(5,2),
    measurement_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_website_referrals FOREIGN KEY (website_id) REFERENCES websites(website_id)
);

-- Social Media Metrics table: Social platform engagement
CREATE TABLE social_media_metrics (
    social_metric_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_id INTEGER NOT NULL,
    platform VARCHAR(50) NOT NULL, -- Facebook, Twitter, LinkedIn, etc.
    followers INTEGER,
    engagement_rate DECIMAL(5,2),
    shares INTEGER,
    likes INTEGER,
    comments INTEGER,
    measurement_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_website_social FOREIGN KEY (website_id) REFERENCES websites(website_id)
);

-- Competitor Analysis table: Competitive intelligence
CREATE TABLE competitor_analysis (
    analysis_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primary_website_id INTEGER NOT NULL,
    competitor_website_id INTEGER NOT NULL,
    similarity_score DECIMAL(5,2), -- 0-100 scale
    audience_overlap DECIMAL(5,2), -- percentage
    market_share DECIMAL(5,2),
    analysis_date DATE NOT NULL,
    notes VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_primary_website FOREIGN KEY (primary_website_id) REFERENCES websites(website_id),
    CONSTRAINT fk_competitor_website FOREIGN KEY (competitor_website_id) REFERENCES websites(website_id),
    CONSTRAINT unique_competitor_pair UNIQUE (primary_website_id, competitor_website_id, analysis_date)
);

-- Create indexes for performance
CREATE INDEX idx_websites_domain ON websites(domain);
CREATE INDEX idx_websites_category ON websites(category_id);
CREATE INDEX idx_websites_active ON websites(is_active);
CREATE INDEX idx_traffic_website ON traffic_metrics(website_id);
CREATE INDEX idx_traffic_date ON traffic_metrics(measurement_date);
CREATE INDEX idx_keywords_website ON keyword_rankings(website_id);
CREATE INDEX idx_keywords_date ON keyword_rankings(measurement_date);
CREATE INDEX idx_referrals_website ON referring_sites(website_id);
CREATE INDEX idx_social_website ON social_media_metrics(website_id);
CREATE INDEX idx_social_platform ON social_media_metrics(platform);
CREATE INDEX idx_competitor_primary ON competitor_analysis(primary_website_id);

-- ============================================
-- Useful Views
-- ============================================

-- View: Latest traffic metrics for each website
CREATE VIEW latest_traffic AS
SELECT 
    w.website_id,
    w.domain,
    w.website_name,
    tm.total_visits,
    tm.unique_visitors,
    tm.bounce_rate,
    tm.avg_visit_duration,
    tm.measurement_date
FROM websites w
INNER JOIN traffic_metrics tm ON w.website_id = tm.website_id
WHERE tm.measurement_date = (
    SELECT MAX(measurement_date)
    FROM traffic_metrics
    WHERE website_id = w.website_id
);

-- View: Website performance summary
CREATE VIEW website_performance_summary AS
SELECT 
    w.website_id,
    w.domain,
    w.website_name,
    w.global_rank,
    c.category_name,
    COUNT(DISTINCT tm.metric_id) as metrics_count,
    AVG(tm.total_visits) as avg_visits,
    AVG(tm.bounce_rate) as avg_bounce_rate,
    MAX(tm.measurement_date) as last_measurement
FROM websites w
LEFT JOIN categories c ON w.category_id = c.category_id
LEFT JOIN traffic_metrics tm ON w.website_id = tm.website_id
GROUP BY w.website_id, w.domain, w.website_name, w.global_rank, c.category_name;

-- View: Top referring sources
CREATE VIEW top_referring_sources AS
SELECT 
    w.domain as target_domain,
    rs.referring_domain,
    rs.referral_visits,
    rs.referral_percentage,
    rs.measurement_date
FROM referring_sites rs
INNER JOIN websites w ON rs.website_id = w.website_id
ORDER BY rs.referral_visits DESC;

-- ============================================
-- Sample Data
-- ============================================

-- Insert sample categories
INSERT INTO categories (category_name, description) VALUES
('E-commerce', 'Online retail and shopping websites'),
('News & Media', 'News portals and media websites'),
('Technology', 'Technology and software companies'),
('Social Media', 'Social networking platforms'),
('Finance', 'Banking and financial services');

-- Insert sample websites
INSERT INTO websites (domain, website_name, category_id, country, global_rank, is_active) VALUES
('example.com', 'Example Website', 1, 'USA', 1500, TRUE),
('techsite.com', 'Tech Site', 3, 'USA', 2300, TRUE),
('newsportal.com', 'News Portal', 2, 'USA', 5000, TRUE);

-- Insert sample traffic metrics
INSERT INTO traffic_metrics (website_id, measurement_date, total_visits, unique_visitors, 
    page_views, pages_per_visit, avg_visit_duration, bounce_rate, 
    direct_traffic_pct, referral_traffic_pct, search_traffic_pct) VALUES
(1, CURRENT_DATE, 1500000, 1200000, 4500000, 3.5, 240, 45.5, 25.0, 15.0, 45.0),
(2, CURRENT_DATE, 800000, 650000, 2400000, 3.2, 180, 52.3, 30.0, 10.0, 50.0),
(3, CURRENT_DATE, 2000000, 1600000, 6000000, 3.8, 300, 40.2, 20.0, 20.0, 48.0);

-- Insert sample keyword rankings
INSERT INTO keyword_rankings (website_id, keyword, ranking_position, search_volume, measurement_date) VALUES
(1, 'online shopping', 5, 50000, CURRENT_DATE),
(2, 'technology news', 3, 30000, CURRENT_DATE),
(3, 'breaking news', 8, 100000, CURRENT_DATE);

-- Insert sample referring sites
INSERT INTO referring_sites (website_id, referring_domain, referral_visits, referral_percentage, measurement_date) VALUES
(1, 'google.com', 150000, 10.0, CURRENT_DATE),
(1, 'facebook.com', 75000, 5.0, CURRENT_DATE),
(2, 'reddit.com', 80000, 10.0, CURRENT_DATE);

COMMIT;

-- ============================================
-- Stored Procedures / Functions (if needed)
-- ============================================

-- This completes the initialization
EOF

    print_success "SQL initialization script created at ${SCRIPT_DIR}/sql/init_similarweb_db.sql"
}

# Function to start HSQLDB server
start_server() {
    if [ -f "$PID_FILE" ]; then
        OLD_PID=$(cat "$PID_FILE")
        if ps -p "$OLD_PID" > /dev/null 2>&1; then
            print_warning "HSQLDB server is already running (PID: $OLD_PID)"
            return
        else
            print_warning "Removing stale PID file"
            rm -f "$PID_FILE"
        fi
    fi
    
    print_info "Starting HSQLDB server on port $SERVER_PORT..."
    
    nohup java -cp "$HSQLDB_JAR" org.hsqldb.server.Server \
        --database.0 "file:$DB_PATH" \
        --dbname.0 "$DB_NAME" \
        --port "$SERVER_PORT" \
        > "$LOG_DIR/hsqldb_server.log" 2>&1 &
    
    SERVER_PID=$!
    echo $SERVER_PID > "$PID_FILE"
    
    # Wait for server to start
    sleep 3
    
    if ps -p "$SERVER_PID" > /dev/null 2>&1; then
        print_success "HSQLDB server started successfully (PID: $SERVER_PID)"
        print_info "Connection URL: jdbc:hsqldb:hsql://localhost:$SERVER_PORT/$DB_NAME"
    else
        print_error "Failed to start HSQLDB server. Check logs at $LOG_DIR/hsqldb_server.log"
        exit 1
    fi
}

# Function to initialize database schema
initialize_database() {
    print_info "Initializing database schema..."
    
    # Wait a bit more to ensure server is ready
    sleep 2
    
    # Try using SqlTool first, if not available use direct JDBC connection
    if [ -f "$SQLTOOL_JAR" ]; then
        java -cp "$HSQLDB_JAR:$SQLTOOL_JAR" org.hsqldb.cmdline.SqlTool \
            --inlineRc="url=jdbc:hsqldb:hsql://localhost:$SERVER_PORT/$DB_NAME,user=SA,password=" \
            "${SCRIPT_DIR}/sql/init_similarweb_db.sql" 2>&1 | tee "$LOG_DIR/init_db.log"
        
        if [ ${PIPESTATUS[0]} -eq 0 ]; then
            print_success "Database schema initialized successfully"
            return
        fi
    fi
    
    # Fallback: Create and use a simple Java SQL executor
    print_info "Using alternative initialization method..."
    create_and_run_sql_executor
}

# Function to create a simple SQL executor
create_and_run_sql_executor() {
    print_info "Creating SQL executor..."
    
    mkdir -p "${SCRIPT_DIR}/temp"
    
    cat > "${SCRIPT_DIR}/temp/SQLExecutor.java" << 'JAVAEOF'
import java.io.*;
import java.sql.*;
import java.nio.file.*;

public class SQLExecutor {
    public static void main(String[] args) {
        if (args.length < 4) {
            System.err.println("Usage: SQLExecutor <url> <user> <password> <sqlfile>");
            System.exit(1);
        }
        
        String url = args[0];
        String user = args[1];
        String password = args[2];
        String sqlFile = args[3];
        
        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            
            String sql = new String(Files.readAllBytes(Paths.get(sqlFile)));
            
            try (Connection conn = DriverManager.getConnection(url, user, password);
                 Statement stmt = conn.createStatement()) {
                
                // Split by semicolon and execute each statement
                String[] statements = sql.split(";");
                int count = 0;
                
                for (String statement : statements) {
                    statement = statement.trim();
                    if (!statement.isEmpty() && !statement.startsWith("--")) {
                        try {
                            stmt.execute(statement);
                            count++;
                        } catch (SQLException e) {
                            System.err.println("Warning: " + e.getMessage());
                        }
                    }
                }
                
                System.out.println("Successfully executed " + count + " SQL statements");
                System.exit(0);
            }
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }
}
JAVAEOF

    # Compile
    print_info "Compiling SQL executor..."
    javac -cp "$HSQLDB_JAR" "${SCRIPT_DIR}/temp/SQLExecutor.java" 2>&1 | tee "$LOG_DIR/compile.log"
    
    if [ ${PIPESTATUS[0]} -ne 0 ]; then
        print_error "Failed to compile SQL executor"
        exit 1
    fi
    
    # Run
    print_info "Executing SQL script..."
    java -cp "$HSQLDB_JAR:${SCRIPT_DIR}/temp" SQLExecutor \
        "jdbc:hsqldb:hsql://localhost:$SERVER_PORT/$DB_NAME" \
        "SA" \
        "" \
        "${SCRIPT_DIR}/sql/init_similarweb_db.sql" 2>&1 | tee "$LOG_DIR/init_db.log"
    
    if [ ${PIPESTATUS[0]} -eq 0 ]; then
        print_success "Database schema initialized successfully"
        rm -rf "${SCRIPT_DIR}/temp"
    else
        print_error "Failed to initialize database schema. Check logs at $LOG_DIR/init_db.log"
        exit 1
    fi
}

# Function to create management scripts
create_management_scripts() {
    print_info "Creating management scripts..."
    
    # Stop script
    cat > "${SCRIPT_DIR}/stop_${DB_NAME}.sh" << EOF
#!/bin/bash
PID_FILE="${PID_FILE}"

if [ -f "\$PID_FILE" ]; then
    PID=\$(cat "\$PID_FILE")
    if ps -p "\$PID" > /dev/null 2>&1; then
        echo "Stopping HSQLDB server (PID: \$PID)..."
        kill \$PID
        sleep 2
        if ps -p "\$PID" > /dev/null 2>&1; then
            echo "Force killing..."
            kill -9 \$PID
        fi
        rm -f "\$PID_FILE"
        echo "HSQLDB server stopped"
    else
        echo "Server is not running"
        rm -f "\$PID_FILE"
    fi
else
    echo "PID file not found. Server may not be running"
fi
EOF
    
    # Restart script
    cat > "${SCRIPT_DIR}/restart_${DB_NAME}.sh" << EOF
#!/bin/bash
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

"\$SCRIPT_DIR/stop_${DB_NAME}.sh"
sleep 2
"\$SCRIPT_DIR/setup_${DB_NAME}.sh" --start-only
EOF
    
    # Status script
    cat > "${SCRIPT_DIR}/status_${DB_NAME}.sh" << EOF
#!/bin/bash
PID_FILE="${PID_FILE}"

if [ -f "\$PID_FILE" ]; then
    PID=\$(cat "\$PID_FILE")
    if ps -p "\$PID" > /dev/null 2>&1; then
        echo "HSQLDB server is running (PID: \$PID)"
        echo "Port: $SERVER_PORT"
        echo "Database: $DB_NAME"
        echo "Connection: jdbc:hsqldb:hsql://localhost:$SERVER_PORT/$DB_NAME"
    else
        echo "HSQLDB server is not running (stale PID file found)"
    fi
else
    echo "HSQLDB server is not running"
fi
EOF
    
    chmod +x "${SCRIPT_DIR}/stop_${DB_NAME}.sh"
    chmod +x "${SCRIPT_DIR}/restart_${DB_NAME}.sh"
    chmod +x "${SCRIPT_DIR}/status_${DB_NAME}.sh"
    
    print_success "Management scripts created"
}

# Function to create connection info file
create_connection_info() {
    cat > "${SCRIPT_DIR}/CONNECTION_INFO.txt" << EOF
========================================
HSQLDB SimilarWeb Database Connection
========================================

JDBC URL: jdbc:hsqldb:hsql://localhost:$SERVER_PORT/$DB_NAME
Username: SA
Password: (empty)
Driver Class: org.hsqldb.jdbc.JDBCDriver

Database Path: $DB_PATH
Server Port: $SERVER_PORT
Log Directory: $LOG_DIR

Management Scripts:
- Start: ./setup_${DB_NAME}.sh --start-only
- Stop: ./stop_${DB_NAME}.sh
- Restart: ./restart_${DB_NAME}.sh
- Status: ./status_${DB_NAME}.sh

GUI Manager:
java -cp $HSQLDB_JAR org.hsqldb.util.DatabaseManager

SQL Tool:
java -cp $HSQLDB_JAR org.hsqldb.util.SqlTool \\
  --inlineRc=url=jdbc:hsqldb:hsql://localhost:$SERVER_PORT/$DB_NAME,user=SA,password=

========================================
EOF
    
    print_success "Connection info saved to ${SCRIPT_DIR}/CONNECTION_INFO.txt"
}

# Main execution
main() {
    echo "=========================================="
    echo "HSQLDB SimilarWeb Database Setup"
    echo "=========================================="
    echo ""
    
    # Parse command line arguments
    START_ONLY=false
    if [ "$1" == "--start-only" ]; then
        START_ONLY=true
    fi
    
    if [ "$START_ONLY" == false ]; then
        check_java
        create_directories
        download_hsqldb
        create_init_sql
        create_management_scripts
        create_connection_info
    fi
    
    start_server
    
    if [ "$START_ONLY" == false ]; then
        initialize_database
        
        echo ""
        echo "=========================================="
        print_success "Setup completed successfully!"
        echo "=========================================="
        echo ""
        echo "Connection Details:"
        echo "  URL: jdbc:hsqldb:hsql://localhost:$SERVER_PORT/$DB_NAME"
        echo "  User: SA"
        echo "  Password: (empty)"
        echo ""
        echo "Management Commands:"
        echo "  Stop server: ./stop_${DB_NAME}.sh"
        echo "  Restart: ./restart_${DB_NAME}.sh"
        echo "  Status: ./status_${DB_NAME}.sh"
        echo ""
        echo "Logs: $LOG_DIR/"
        echo "=========================================="
    fi
}

# Run main function
main "$@"
